### PR TITLE
Support Aliyun OSS

### PR DESCRIPTION
**Pull request by denverdino**
Support Alibaba Cloud OSS as external storage

### CODE REVIEW

**Comment by BorisPolonsky** [comment]
Thanks for your contribution. I'm currently very busy and my k8s dev environment went down hence I have to review this later. Sorry for the delay.

**Comment by BorisPolonsky** [comment]
LGTM. Since we need to further adjust some comments and precedence of the configuration in `.Values.yaml` and we have other features that need to be overhauled, could you please merge into `dev` branch instead? Thank you.

**Comment by denverdino** [comment]
Thanks for your review. I changed the base branch to dev.

**Comment by BorisPolonsky** [comment]
@denverdino Could you please confirm if `OSS` were officially supported by `dify`. There's no such environment variables in their exemplar [docker-compoese.yaml](https://github.com/langgenius/dify/blob/main/docker/docker-compose.yaml)

**Comment by denverdino** [comment]
@BorisPolonsky Yes, it is defined in 
https://github.com/langgenius/dify/blob/main/api/config.py#L245

And examples in
https://github.com/langgenius/dify/blob/main/api/.env.example#L57

and I tested it for a while and fixed few issues months ago. https://github.com/langgenius/dify/pull/4425

**Comment by BorisPolonsky** [comment]
Noted. It would be advisable if you would also add these configuration to their `docker-compose.yaml` as we aim to maintain compatibility based on that file.

**Comment by denverdino** [comment]
https://github.com/langgenius/dify/pull/5366

The PR has been merged.

**Pull request merged**
