### PR TITLE
(feat) Add support for smtp config

### PR DESCRIPTION
**Pull request by filipechagas**
## Add Support for SMTP config

If api.mail.type eq `smtp`, it'll allow the definition of smtp config env vars.

https://docs.dify.ai/getting-started/install-self-hosted/environments#mail-related-configuration

### CODE REVIEW

**Comment by BorisPolonsky** [comment]
Thanks for your contribution. 
I wonder if it's a good idea to substitute `.Values.api.mail.smtp.*` pattern for `.Values.api.mail.smtp` in [this section](https://github.com/filipechagas/dify-helm/blob/master/charts/dify/templates/config.tpl#L254-L258), what do you think?
Meanwhile, it's advise update `.Values.yaml` as well to make this feature explicit. A dummy example with comments will be helpful.

**Comment by filipechagas** [comment]
@BorisPolonsky Makes sense. Thank you for the feedback. I've applied the suggestions - did the same for resend moving it from `api.mail.resendApi*` to `api.mail.resend.api*`. LMK what you think.

**Comment by BorisPolonsky** [comment]
LGTM. We are closed to merging this PR. 
It's also advised to make [this value](https://github.com/filipechagas/dify-helm/blob/master/charts/dify/templates/config.tpl#L258) `boolean` instead of `string` and substitute 
`{{ .Values.api.mail.smtp.useTLS | quote }` for `{{ .Values.api.mail.smtp.useTLS | toString | quote }`. Just like `MILVUS_SECURE` does.

**Comment by filipechagas** [comment]
@BorisPolonsky Good thinking. Done f2c1b33e20d1a48f1361afa5bef16942008766cd

**Pull request merged**
